### PR TITLE
Pin @svgr/cli instead of using npx

### PR DESCRIPTION
**Pull request by youngmanalive**
### Context
When running the cli, instead of having a pinned dependency, we were using `npx @svgr/cli`, which always pulls the latest. for some reason this was causing a build failure due to something with our forked `create-index` thing. 

### Solution
- Pin `@svgr/cli v4.3.3`
- Update scripts to `svgr ....` instead of `npx @svgr/cli ....`

### CODE REVIEW

**Comment by youngmanalive** [comment]
This might do it.

**Comment by youngmanalive** [comment]
I believe that is what the update flag is doing...
```
--update, -u             
Updates only previously created index files (recursively). [boolean] [default: false]
```

how did it break in the first place?...

**Comment by michaeljaltamirano** [comment]
Installing @svgr/cli@4.3.3 (last version before 5) so that package.json looks like this:

```
    "build:icons:icons": "svgr --expand-props none --template src/utils/svgToIconTemplate/index.js -d src/icons/ src/svgs/icons/",
    "build:icons:emojis": "svgr --expand-props none --template src/utils/svgToIconTemplate/index.js -d src/icons/ src/svgs/emojis/",
    "build:icons:glyphs": "svgr --expand-props none --template src/utils/svgToIconTemplate/index.js -d src/icons/ src/svgs/glyphs/",
```

And removing the --update flag, seems to create the `index.js` file the way we expect:

```
// @create-index

export { default as AcneFewGlyph } from './AcneFewGlyph.js';
export { default as AcneGlyph } from './AcneGlyph.js';
export { default as AcneManyGlyph } from './AcneManyGlyph.js';
export { default as AcneSeveralGlyph } from './AcneSeveralGlyph.js';
export { default as AcneSomeGlyph } from './AcneSomeGlyph.js';
export { default as AnxiousEmoji } from './AnxiousEmoji.js';
export { default as AnxiousFilledEmoji } from './AnxiousFilledEmoji.js';
export { default as ArrowLeftIcon } from './ArrowLeftIcon.js';
export { default as ArrowRightIcon } from './ArrowRightIcon.js';
export { default as AzelaicAcidGlyph } from './AzelaicAcidGlyph.js';
export { default as BodyGlyph } from './BodyGlyph.js';
export { default as CalendarIcon } from './CalendarIcon.js';
export { default as CameraIcon } from './CameraIcon.js';
export { default as ChatBubbleGlyph } from './ChatBubbleGlyph.js';
export { default as CheckBadgeGlyph } from './CheckBadgeGlyph.js';
export { default as CheckmarkCircleIcon } from './CheckmarkCircleIcon.js';
export { default as CheckmarkIcon } from './CheckmarkIcon.js';
export { default as ChevronIcon } from './ChevronIcon.js';
export { default as ClindamycinGlyph } from './ClindamycinGlyph.js';
export { default as ClipboardIcon } from './ClipboardIcon.js';
export { default as ClipboardStackGlyph } from './ClipboardStackGlyph.js';
export { default as CloggedPoresGlyph } from './CloggedPoresGlyph.js';
export { default as CloseIcon } from './CloseIcon.js';
export { default as CombinationGlyph } from './CombinationGlyph.js';
export { default as ConfusedEmoji } from './ConfusedEmoji.js';
export { default as CourseGlyph } from './CourseGlyph.js';
export { default as CreditCardIcon } from './CreditCardIcon.js';
export { default as DarkSpotsGlyph } from './DarkSpotsGlyph.js';
export { default as DeleteIcon } from './DeleteIcon.js';
export { default as DownloadIcon } from './DownloadIcon.js';
export { default as DropIcon } from './DropIcon.js';
export { default as DropletIcon } from './DropletIcon.js';
export { default as DropperGlyph } from './DropperGlyph.js';
export { default as EditIcon } from './EditIcon.js';
export { default as ElatedEmoji } from './ElatedEmoji.js';
export { default as ElatedFilledEmoji } from './ElatedFilledEmoji.js';
export { default as EqualsIcon } from './EqualsIcon.js';
export { default as ErrorIcon } from './ErrorIcon.js';
export { default as EyeClosedIcon } from './EyeClosedIcon.js';
export { default as FaceGlyph } from './FaceGlyph.js';
export { default as FacebookIcon } from './FacebookIcon.js';
export { default as FacebookSquareIcon } from './FacebookSquareIcon.js';
export { default as FemaleGlyph } from './FemaleGlyph.js';
export { default as FirmnessGlyph } from './FirmnessGlyph.js';
export { default as FirstAidIcon } from './FirstAidIcon.js';
export { default as FlagIcon } from './FlagIcon.js';
export { default as FuriousEmoji } from './FuriousEmoji.js';
export { default as FuriousFilledEmoji } from './FuriousFilledEmoji.js';
export { default as GeneralQuestionsGlyph } from './GeneralQuestionsGlyph.js';
export { default as GiftIcon } from './GiftIcon.js';
export { default as GoogleIcon } from './GoogleIcon.js';
export { default as HandWritingGlyph } from './HandWritingGlyph.js';
export { default as HeartEmoji } from './HeartEmoji.js';
export { default as HeartFilledEmoji } from './HeartFilledEmoji.js';
export { default as HeartIcon } from './HeartIcon.js';
export { default as HugEmoji } from './HugEmoji.js';
export { default as HugFilledEmoji } from './HugFilledEmoji.js';
export { default as InfoIcon } from './InfoIcon.js';
export { default as InstagramIcon } from './InstagramIcon.js';
export { default as LockGlyph } from './LockGlyph.js';
export { default as LockIcon } from './LockIcon.js';
export { default as LogoCIcon } from './LogoCIcon.js';
export { default as LogoCondensedIcon } from './LogoCondensedIcon.js';
export { default as LogoIcon } from './LogoIcon.js';
export { default as LogoutIcon } from './LogoutIcon.js';
export { default as MailIcon } from './MailIcon.js';
export { default as MaleGlyph } from './MaleGlyph.js';
export { default as MenuIcon } from './MenuIcon.js';
export { default as MessageIcon } from './MessageIcon.js';
export { default as MildAcneEmoji } from './MildAcneEmoji.js';
export { default as MinusIcon } from './MinusIcon.js';
export { default as MoreIcon } from './MoreIcon.js';
export { default as MortorGlyph } from './MortorGlyph.js';
export { default as NeckGlyph } from './NeckGlyph.js';
export { default as NiacinamideGlyph } from './NiacinamideGlyph.js';
export { default as NoMakeupGlyph } from './NoMakeupGlyph.js';
export { default as NoneGlyph } from './NoneGlyph.js';
export { default as NoticeableAcneEmoji } from './NoticeableAcneEmoji.js';
export { default as NotificationsIcon } from './NotificationsIcon.js';
export { default as OftenDryGlyph } from './OftenDryGlyph.js';
export { default as OftenOilyGlyph } from './OftenOilyGlyph.js';
export { default as OtherGlyph } from './OtherGlyph.js';
export { default as OverwhelmedEmoji } from './OverwhelmedEmoji.js';
export { default as OverwhelmedFilledEmoji } from './OverwhelmedFilledEmoji.js';
export { default as PaperclipIcon } from './PaperclipIcon.js';
export { default as PhotosIcon } from './PhotosIcon.js';
export { default as PillsGlyph } from './PillsGlyph.js';
export { default as PlanIcon } from './PlanIcon.js';
export { default as PlayIcon } from './PlayIcon.js';
export { default as PlusIcon } from './PlusIcon.js';
export { default as PostcardIcon } from './PostcardIcon.js';
export { default as PreparedEmoji } from './PreparedEmoji.js';
export { default as PreparedFilledEmoji } from './PreparedFilledEmoji.js';
export { default as QuestionCircleIcon } from './QuestionCircleIcon.js';
export { default as SatisfiedEmoji } from './SatisfiedEmoji.js';
export { default as SatisfiedFilledEmoji } from './SatisfiedFilledEmoji.js';
export { default as SelfieGlyph } from './SelfieGlyph.js';
export { default as SevereAcneEmoji } from './SevereAcneEmoji.js';
export { default as SkinTextureGlyph } from './SkinTextureGlyph.js';
export { default as SmileIcon } from './SmileIcon.js';
export { default as SpaceshipGlyph } from './SpaceshipGlyph.js';
export { default as SparkleEmoji } from './SparkleEmoji.js';
export { default as SparkleFilledEmoji } from './SparkleFilledEmoji.js';
export { default as StarFilledIcon } from './StarFilledIcon.js';
export { default as StarIcon } from './StarIcon.js';
export { default as SunGlyph } from './SunGlyph.js';
export { default as SunscreenBottleGlyph } from './SunscreenBottleGlyph.js';
export { default as SunscreenDropGlyph } from './SunscreenDropGlyph.js';
export { default as SunscreenTubGlyph } from './SunscreenTubGlyph.js';
export { default as SupportCenterGlyph } from './SupportCenterGlyph.js';
export { default as SupportedEmoji } from './SupportedEmoji.js';
export { default as SupportedFilledEmoji } from './SupportedFilledEmoji.js';
export { default as ThumbsDownIcon } from './ThumbsDownIcon.js';
export { default as ThumbsUpIcon } from './ThumbsUpIcon.js';
export { default as TretinoinGlyph } from './TretinoinGlyph.js';
export { default as TruckIcon } from './TruckIcon.js';
export { default as TwitterIcon } from './TwitterIcon.js';
export { default as UnsatisfiedEmoji } from './UnsatisfiedEmoji.js';
export { default as UnsatisfiedFilledEmoji } from './UnsatisfiedFilledEmoji.js';
export { default as VeryDryGlyph } from './VeryDryGlyph.js';
export { default as VeryOilyGlyph } from './VeryOilyGlyph.js';
export { default as VitaminCGlyph } from './VitaminCGlyph.js';
export { default as WrinklesGlyph } from './WrinklesGlyph.js';
export { default as ZincGlyph } from './ZincGlyph.js';
```

**Comment by youngmanalive** [comment]
oh interesting!!! good looking. i was def wary that this was fixing the underlying issue. odd that we chose the npx route. Lemme update this.

**Comment by ZeMunchkin** [comment]
Just adding a comment about versioning number -- If yo do a release with this, number it 4.X.X, not 5.X.X. Diego has a partial TS release under 5 which isn't ready yet, it's from a different branch, but we don't want to cross versioning numbers

https://github.com/PocketDerm/radiance-ui/pull/175#pullrequestreview-348888160

**Comment by cmgmyr** [comment]
#173, #179 can be released too

**Comment by youngmanalive** [comment]
> LGTM. Let's update the PR title (and description, accordingly).
> 
> The `svgr` usage docs suggest using `npx` for usage even after installing, which explains why it was set up that way in our `package.json`. Hopefully this works without issue and now we have more clarity with the toolchain here 🙂

the cli package [readme example](https://github.com/gregberge/svgr/tree/master/packages/cli) doesn't include the `npx` call. i like using npx for things like `create-react-app`, but curious why it'd be used in this scenario 🤔. 

good catch spotting all of this!

**Pull request merged**
