### PR TITLE
Box Shadow Examples

### PR DESCRIPTION
**Pull request by daigof**
- It made sense to add this to Constants section like Colors examples
- I also refactored/cleaned up the Colors Story

### CODE REVIEW

**Comment by snags88** [comment]
Could we do a similar thing as Colors where we categorize the box shadow examples by context (e.g. legacyColors, brandColors, etc.). I think for box shadows, we have few different ones like Base config, alias config etc

**Comment by daigof** [comment]
@snags88 yep done

**Comment by snags88** [comment]
@daigof i'm not seeing the values or the box shadow on the story now:
Screen Shot 2019-04-25 at 1 50 18 PM

**Comment by daigof** [comment]
ughh sorry, fixed

**Pull request merged**
